Feat/solana wallet adapter
holaplex/holaplex pull request #219
Opened 2022-02-16 14:08 UTC by ArpitAgrawal321

This PR:-

- Removes all instances of window.solana and replaces them with methods provided by solana wallet adapter.
- Updated various methods to use wallet adapter.

2022-02-18 21:55 UTC, kespinola commented
@ArpitAgrawal321 thanks so much for this. I'm going to get it across the line for you.

2022-02-21 06:23 UTC, metallicalfa2 commented
@kespinola  Further comments:
- Currently, in the dev setup, the network for the adapters is hardcoded to mainnet. (in _app.tsx)
- All the adapter method return a Uint8Array. We should update the Signers to use the same instead of Buffer. 
- Support >= node@16 instead of specific node version (is there a reason for this ?)

2022-02-21 16:32 UTC, kevinrodriguez-io requested changes
Looks good overall; please address the given comments, I'll run some end to end tests to check everything is working fine.

2022-02-21 16:32 UTC, kevinrodriguez-io commented on pages/storefront/edit.tsx
> +            <Button type="primary" block onClick={()=>connect()}>
```suggestion
            <Button type="primary" block onClick={() => connect()}>
```

2022-02-21 16:32 UTC, kevinrodriguez-io commented on pages/storefront/edit.tsx
> +  const subdomainUniqueness = validateSubdomainUniqueness(ar, publicKey?.toString());
We probably want to check there's a pubKey before reaching this point, but I'm not pretty sure

2022-02-21 16:32 UTC, kevinrodriguez-io commented on pages/storefront/new.tsx
> +            <Button type="primary" block onClick={()=>connect()}>
```suggestion
            <Button type="primary" block onClick={() => connect()}>
```

2022-02-21 16:32 UTC, kevinrodriguez-io commented on src/common/components/elements/Upload.tsx
> +  const contextState = useWallet();
Weird name, shouldn't it just be wallet?

2022-02-21 16:32 UTC, kevinrodriguez-io commented on src/modules/arweave/upload.ts
> +    const notarized: ArweaveUploadParams = await notarize(payload, wallet.signMessage as Signer, {
This really works?

2022-02-21 16:32 UTC, kevinrodriguez-io commented on src/modules/storefront/provider.tsx
> +  const { publicKey} = useWallet();
```suggestion
  const { publicKey } = useWallet();
```

2022-02-21 16:32 UTC, kevinrodriguez-io commented on src/modules/storefront/provider.tsx
> +    const pub_key = publicKey?.toString();
```suggestion
    const pubKey = publicKey?.toString();
```

2022-02-21 16:32 UTC, kevinrodriguez-io commented on src/modules/storefront/provider.tsx
> +      .storefront.find('solana:pubkey', pub_key)
```suggestion
      .storefront.find('solana:pubkey', pubKey)
```

2022-02-21 16:32 UTC, kevinrodriguez-io commented on src/modules/wallet/provider.tsx
>        return walletSDK.create(pubkey);
We probably also want to get rid of this walletSDK thing

2022-02-21 16:32 UTC, kevinrodriguez-io commented on src/modules/wallet/provider.tsx
> +            return router.push(path);
```suggestion
  useEffect(() => {
    (async () => {
      if (connected && publicKey) {
        setVerifying(true);
        try {
          const pubKey = publicKey?.toString();
          if (!pubKey) throw new Error('Wallet not connected');
          await upsertWallet(pubKey);
          
          const sf = await arweaveSDK.using(arweave).storefront.find('solana:pubkey', pubKey);
          if (sf) setStorefront(sf);
          setVerifying(false);
          if (redirect.current) {
            const path = redirect.current;
            redirect.current = '';
            return router.push(path);
```

2022-02-22 00:18 UTC, kespinola commented
We got all this changes in on this PR. A few moving pieces right now for us.

https://github.com/holaplex/holaplex/pull/224

2022-02-22 00:18 UTC, closed without merging