Fix: Offer Tab Ordering
holaplex/holaplex pull request #357
Opened 2022-04-20 21:12 UTC by PedroLealLopes

should fix issue #353 not 100% sure cause I couldn't get the development environment fully set up 😅

2022-04-21 08:47 UTC, kristianeboe requested changes
Hi Pedro, thanks for the commit! I left a few, hopefully helpful, comments in the review. Also, please let us know what was the problem with setting up the project locally. We'd like to help!

2022-04-21 08:47 UTC, kristianeboe commented on pages/profiles/[publicKey]/offers.tsx
> +  function byDate(a: any, b: any) {
Please use types here :)

2022-04-21 08:47 UTC, kristianeboe commented on pages/profiles/[publicKey]/offers.tsx
> +    return new Date(a.createdAt).valueOf() - new Date(b.createdAt).valueOf(); //timestamps
Please use .getTime() insetad of .valueOf() -> https://bobbyhadz.com/blog/javascript-convert-iso-date-to-timestamp#:~:text=Use%20the%20getTime()%20method,uses%20UTC%20for%20time%20representation.

or look into using the library https://moment.github.io/luxon/ like we use other places, search for `import { DateTime } from 'luxon'`

2022-04-21 08:47 UTC, kristianeboe commented on pages/profiles/[publicKey]/offers.tsx
> +                .reverse()
You can just reverse the sorting function instead of tacking on a reverse() here :)

2022-04-21 08:47 UTC, kristianeboe commented on pages/profiles/[publicKey]/offers.tsx
> +                .reverse()
Same as above

2022-04-21 19:20 UTC, PedroLealLopes commented
Regarding the development environment, the seed command does not work.

this is the response of `yarn db:seed`
![CB4AEDEC-E74C-496F-9AAD-9106704E52CA](https://user-images.githubusercontent.com/62293164/164536989-b9482ccf-87ad-4015-82d9-e658f35c88cb.png)

2022-04-21 20:13 UTC, austinmilt commented
> 

you dont need to run the seed command to get the app up and running. Try `yarn dev2`

2022-04-21 22:18 UTC, PedroLealLopes commented
Oh ok then local development environment works just fine!

2022-04-22 09:22 UTC, kristianeboe approved these changes

2022-04-22 09:22 UTC, merged